apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: typescript-api

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- deployment.yaml
- hpa.yaml
- ingress.yaml

commonLabels:
  app: typescript-api
  version: v1.0.0
  environment: production

images:
- name: typescript-api
  newTag: latest